name: Docker Image CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 4 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - major: 7.2
            variant: cli
          - major: 7.4
            variant: crm
          - major: 7.4
            variant: srv
          - major: 7.4
            variant: sso
          - major: 7.4
            variant: cli
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set variables
        id: vars
        working-directory: ${{ matrix.major }}/${{ matrix.variant }}
        run: |
          echo "repository=${GITHUB_ACTOR}/$(basename ${GITHUB_REPOSITORY})" >> $GITHUB_OUTPUT
          echo "version=$(grep 'PHP_VERSION=' Dockerfile | awk -F '[=.]' '{print $2"."$3"."$4}')" >> $GITHUB_OUTPUT
          echo "workdir=${{ matrix.major }}/${{ matrix.variant }}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ steps.vars.outputs.workdir }}
          pull: true
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.vars.outputs.repository }}:${{ matrix.major }}-${{ matrix.variant }}
            ${{ steps.vars.outputs.repository }}:${{ steps.vars.outputs.version }}-${{ matrix.variant }}
