name: Docker Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 1 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - major: 7.2
            variant: srv
          - major: 7.2
            variant: sso
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the Docker image
        working-directory: ${{ matrix.major }}/${{ matrix.variant }}
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build \
          --pull \
          --file Dockerfile \
          --tag chinayin/php-deploy:${{ matrix.major }}-${{ matrix.variant }} \
          .
      - name: Push image to Docker hub
        if: success()
        working-directory: ${{ matrix.major }}/${{ matrix.variant }}
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
          docker push chinayin/php-deploy:${{ matrix.major }}-${{ matrix.variant }}
          docker logout
